name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'

env:
  RESOURCE_GROUP: rg-myenv
  LOCATION: eastus

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Bicep infrastructure
        run: |
          az deployment sub create \
            --location ${{ env.LOCATION }} \
            --template-file ./infra/main.bicep \
            --parameters ./infra/main.parameters.json \
            --parameters \
              location=${{ env.LOCATION }} \
              resourceGroupName=${{ env.RESOURCE_GROUP }}

    #   - name: Output Infrastructure Details
    #     run: |
    #       echo "Infrastructure deployment complete. Resource details:"
          
    #       # Get Container Registry endpoint
    #       ACR_ENDPOINT=$(az deployment sub show \
    #         --name main \
    #         --query properties.outputs.AZURE_CONTAINER_REGISTRY_ENDPOINT.value \
    #         -o tsv)
    #       echo "Container Registry Endpoint: $ACR_ENDPOINT"
          
    #       # Calculate resource names based on token
    #       SUBSCRIPTION_ID=$(az account show --query id -o tsv)
    #       RESOURCE_TOKEN=$(echo -n "$SUBSCRIPTION_ID:${{ env.LOCATION }}:${{ env.RESOURCE_GROUP }}" | sha1sum | cut -c1-8)
          
    #       # Output resource names
    #       echo "Resource Token: $RESOURCE_TOKEN"
    #       echo "Container Apps Environment: env$RESOURCE_TOKEN"
    #       echo "Key Vault: kv$RESOURCE_TOKEN"
    #       echo "Cosmos DB: db0$RESOURCE_TOKEN"
