name: Deploy Task Tracker to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure infrastructure
        id: deploy_infra
        run: |
          echo "Creating resource group and deploying infrastructure..."
          DEPLOYMENT_NAME="task-tracker-$(date +%s)"
          az deployment sub create \
            --name $DEPLOYMENT_NAME \
            --location eastus \
            --template-file ./infrastructure/main.bicep \
            --parameters location=eastus resourceGroupName=rg-tasktracker-dev
          
          echo "Waiting for deployment to complete..."
          az deployment sub wait --name $DEPLOYMENT_NAME --created
          
          # Get the ACR name from the deployment output
          ACR_NAME=$(az deployment sub show --name $DEPLOYMENT_NAME --query properties.outputs.azurE_CONTAINER_REGISTRY_ENDPOINT.value --output tsv | cut -d'.' -f1)
          echo "acr_name=$ACR_NAME" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.acr_name }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.acr_name }}.azurecr.io/tasktracker-backend:${{ github.sha }}
          file: ./backend/Dockerfile

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.acr_name }}.azurecr.io/tasktracker-frontend:${{ github.sha }}
          file: ./frontend/Dockerfile.prod

      - name: Update container apps with new images
        run: |
          # Update backend container app
          BACKEND_APP_NAME=$(az containerapp list -g rg-tasktracker-dev --query "[?contains(name, 'backend')].name" -o tsv)
          az containerapp update \
            -n $BACKEND_APP_NAME \
            -g rg-tasktracker-dev \
            --image ${{ env.acr_name }}.azurecr.io/tasktracker-backend:${{ github.sha }}

          # Update frontend container app
          FRONTEND_APP_NAME=$(az containerapp list -g rg-tasktracker-dev --query "[?contains(name, 'frontend')].name" -o tsv)
          az containerapp update \
            -n $FRONTEND_APP_NAME \
            -g rg-tasktracker-dev \
            --image ${{ env.acr_name }}.azurecr.io/tasktracker-frontend:${{ github.sha }}
